name: em_viz
channels:
  - conda-forge
dependencies:
  - python>=3.7 
  - pyqt=5               
  - pyopengl
  - matplotlib
  - pip
  - pip:
    - git+https://github.com/pyqtgraph/pyqtgraph.git@3ed45751d77cff7c260bf29940950abb6411ed0c
